export const PERMISSIONS = {
  DASHBOARD_ACCESS: "dashboard.access",
  COLEGIOS_MANAGE: "colegios.manage",
  USUARIOS_MANAGE: "usuarios.manage",
  RBAC_MANAGE: "rbac.manage",
  ALUNOS_READ: "alunos.read",
  ALUNOS_MANAGE: "alunos.manage",
  ALUNOS_TRANSFER: "alunos.transfer",
  RESPONSAVEIS_READ: "responsaveis.read",
  RESPONSAVEIS_MANAGE: "responsaveis.manage",
  TURMAS_READ: "turmas.read",
  TURMAS_MANAGE: "turmas.manage",
  ANOS_LETIVOS_MANAGE: "anos_letivos.manage",
  MATRICULAS_READ: "matriculas.read",
  MATRICULAS_MANAGE: "matriculas.manage",
  DISCIPLINA_CATALOGOS_READ: "disciplina.catalogos.read",
  DISCIPLINA_CATALOGOS_MANAGE: "disciplina.catalogos.manage",
  OCORRENCIAS_CREATE: "ocorrencias.create",
  OCORRENCIAS_READ_OWN: "ocorrencias.read.own",
  OCORRENCIAS_READ_SCHOOL: "ocorrencias.read.school",
  OCORRENCIAS_MANAGE: "ocorrencias.manage",
  MANIFESTACOES_CREATE: "manifestacoes.create",
  MANIFESTACOES_AVALIAR: "manifestacoes.avaliar",
  CIENCIAS_CONFIRM: "ciencias.confirm",
  ENQUADRAMENTOS_MANAGE: "enquadramentos.manage",
  DECISOES_REGISTER: "decisoes.register",
  SANCOES_APPLY: "sancoes.apply",
  RECONSIDERACOES_CREATE: "reconsideracoes.create",
  RECONSIDERACOES_DECIDE: "reconsideracoes.decide",
  AFASTAMENTOS_MANAGE: "afastamentos.manage",
  SINDICANCIAS_MANAGE: "sindicancias.manage",
  CONSELHOS_MANAGE: "conselhos.manage",
  ELOGIOS_REGISTER: "elogios.register",
  PONTUACAO_MANAGE: "pontuacao.manage",
  COMPORTAMENTO_READ: "comportamento.read",
  FICHAS_GENERATE: "fichas.generate",
  ANEXOS_MANAGE: "anexos.manage",
  AUDITORIA_READ: "auditoria.read",
  TENANCY_SWITCH: "tenancy.switch",
} as const;

export type PermissionCode = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export const ROLE_CODES = {
  ADMINISTRADOR: "ADMINISTRADOR",
  DIRETOR_PM: "DIRETOR_PM",
  DIRETOR_ADJUNTO: "DIRETOR_ADJUNTO",
  CHEFE_CORPO_ALUNOS: "CHEFE_CORPO_ALUNOS",
  COMANDANTE_COMPANHIA: "COMANDANTE_COMPANHIA",
  COMANDANTE_PELOTAO: "COMANDANTE_PELOTAO",
  PROFESSOR: "PROFESSOR",
  FUNCIONARIO: "FUNCIONARIO",
  MILITAR: "MILITAR",
  RESPONSAVEL: "RESPONSAVEL",
} as const;
